# Generated by Django 3.2.1 on 2021-09-17 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_post',
            name='name',
        ),
        migrations.AddField(
            model_name='category_post',
            name='post_in_category',
            field=models.CharField(choices=[('HL', 'Health'), ('LF', 'Lifestyle'), ('WD', 'Web development'), ('PROG', 'Programming')], default='PROG', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='cat',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogApp.category_post'),
        ),
    ]
