# Generated by Django 3.2.1 on 2021-09-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_auto_20210917_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_post',
            name='post_in_category',
        ),
        migrations.AddField(
            model_name='category_post',
            name='name',
            field=models.CharField(default='Programming', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='post_in_category',
            field=models.CharField(choices=[('HL', 'Health'), ('LF', 'Lifestyle'), ('WD', 'Web development'), ('PROG', 'Programming')], default='PROG', max_length=100),
        ),
    ]
