# Generated by Django 3.2.1 on 2021-09-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_auto_20210917_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cat',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_in_category',
            field=models.CharField(choices=[('Health', 'Health'), ('Life style', 'Lifestyle'), ('Web development', 'Web development'), ('Programming', 'Programming')], default='Programming', max_length=100, unique=True),
        ),
    ]
